services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8069"
    volumes:
      - ./config/odoo.conf:/etc/odoo.conf
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    networks:
      - odoo-net

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: odoo
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - odoo-net

networks:
  odoo-net:
    driver: bridge

volumes:
  db_data: