services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8069"
    volumes:
      - ./config/odoo.conf:/etc/odoo.conf
      - ./custom_addons:/opt/odoo/custom_addon
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=odoo
      - DB_PASSWORD=odoo

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: odoo
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: